// Seed script — adds recipes to the remote API
// Usage: node scripts/seed-recipes.js

const API_URL = 'https://michalovic.endora.site/api/recipes.php';
const API_TOKEN = 'mic-9kX4mW2pR7vL8j';

const BASE_ID = 1745100000000;

function makeId(n) { return BASE_ID + n * 1000; }

const recipes = [
  {
    id: makeId(1), createdAt: makeId(1),
    title: "Švédské kuličky (Köttbullar)",
    description: "Klasické švédské masové kuličky v omáčce",
    emoji: "🍖",
    category: "Hlavní jídla",
    prepTime: 10, cookTime: 40,
    difficulty: "Jednoduché",
    servings: 6,
    notes: "https://cookidoo.cz/created-recipes/public/recipes/cs/01KGH20Z9CWH814SRSG1XE0HKQ",
    ingredients: [
      { name: "Mleté maso", qty: 500, unit: "g" },
      { name: "Cibule", qty: 1, unit: "ks" },
      { name: "Strouhanka", qty: null, unit: "" },
      { name: "Petrželka", qty: null, unit: "" },
      { name: "Vejce", qty: 1, unit: "ks" },
      { name: "Olivový olej", qty: null, unit: "" },
      { name: "Nové koření", qty: null, unit: "" },
      { name: "Muškátový oříšek", qty: null, unit: "" },
      { name: "Česnekový prášek", qty: null, unit: "" },
      { name: "Černý pepř", qty: null, unit: "" },
      { name: "Máslo (omáčka)", qty: null, unit: "" },
      { name: "Hladká mouka (omáčka)", qty: null, unit: "" },
      { name: "Hovězí vývar", qty: null, unit: "" },
      { name: "Zakysaná smetana (omáčka)", qty: null, unit: "" },
      { name: "Worcesterská omáčka", qty: null, unit: "" },
      { name: "Dijonská hořčice", qty: null, unit: "" },
    ],
    steps: [],
  },
  {
    id: makeId(2), createdAt: makeId(2),
    title: "Syrníky",
    description: "Rychlé tvarohové lívanečky",
    emoji: "🥞",
    category: "Snídaně",
    prepTime: 5, cookTime: 10,
    difficulty: "Jednoduché",
    servings: 6,
    notes: "https://cookidoo.cz/created-recipes/public/recipes/cs/01KF3Y7VAE95D80AXTFFZ7H3GW",
    ingredients: [
      { name: "Tvrdý tvaroh", qty: 400, unit: "g" },
      { name: "Vejce", qty: null, unit: "" },
      { name: "Sůl", qty: null, unit: "" },
      { name: "Cukr (3 lžíce)", qty: null, unit: "" },
      { name: "Hladká mouka (5–6 lžic)", qty: null, unit: "" },
    ],
    steps: [],
  },
  {
    id: makeId(3), createdAt: makeId(3),
    title: "Brokolicová rýže",
    description: "Zapečená rýže s brokolicí, kuřecím masem a cheddarem",
    emoji: "🥦",
    category: "Hlavní jídla",
    prepTime: 5, cookTime: 20,
    difficulty: "Jednoduché",
    servings: 8,
    notes: "https://cookidoo.cz/created-recipes/public/recipes/cs/01KF0JG1RCR94S0E7JB0PS08NX",
    ingredients: [
      { name: "Kuřecí prsa", qty: null, unit: "" },
      { name: "Rýže", qty: null, unit: "" },
      { name: "Brokolice", qty: null, unit: "" },
      { name: "Cheddar", qty: null, unit: "" },
      { name: "Smetana na vaření", qty: null, unit: "" },
      { name: "Vývar", qty: null, unit: "" },
      { name: "Cibule", qty: 1, unit: "ks" },
      { name: "Česnek", qty: null, unit: "" },
      { name: "Olivový olej", qty: null, unit: "" },
      { name: "Sůl", qty: null, unit: "" },
      { name: "Pepř", qty: null, unit: "" },
      { name: "Paprika", qty: null, unit: "" },
    ],
    steps: [],
  },
  {
    id: makeId(4), createdAt: makeId(4),
    title: "Kuře na paprice",
    description: "Tradiční kuřecí paprikáš se zakysanou smetanou",
    emoji: "🍗",
    category: "Hlavní jídla",
    prepTime: 10, cookTime: 35,
    difficulty: "Jednoduché",
    servings: 4,
    notes: "https://cookidoo.cz/created-recipes/public/recipes/cs/01K12WFK8YRKAKPZKVW9HHP7YP",
    ingredients: [
      { name: "Kuřecí prsa", qty: 500, unit: "g" },
      { name: "Cibule", qty: 50, unit: "g" },
      { name: "Olej", qty: 15, unit: "g" },
      { name: "Máslo", qty: 15, unit: "g" },
      { name: "Sladká červená paprika (3 lžíce)", qty: null, unit: "" },
      { name: "Bujón (0,5 l)", qty: 1, unit: "ks" },
      { name: "Voda", qty: 1150, unit: "g" },
      { name: "Zakysaná smetana", qty: 200, unit: "g" },
      { name: "Hladká mouka", qty: 40, unit: "g" },
      { name: "Sůl", qty: null, unit: "" },
      { name: "Černý pepř", qty: null, unit: "" },
    ],
    steps: [],
  },
  {
    id: makeId(5), createdAt: makeId(5),
    title: "Boloňské ragů podle Míchalů",
    description: "Domácí boloňská omáčka na špagety",
    emoji: "🍝",
    category: "Hlavní jídla",
    prepTime: 15, cookTime: 30,
    difficulty: "Jednoduché",
    servings: 6,
    notes: "https://cookidoo.cz/created-recipes/public/recipes/cs/01JZYXBVEXK8ZWCMFHY1SZX6BA",
    ingredients: [
      { name: "Cibule", qty: 1, unit: "ks" },
      { name: "Česnek", qty: null, unit: "" },
      { name: "Rostlinný olej (1 lžíce)", qty: null, unit: "" },
      { name: "Rajčatový protlak", qty: 70, unit: "g" },
      { name: "Mleté hovězí maso", qty: 500, unit: "g" },
      { name: "Bazalka (sušená, 1 lžička)", qty: null, unit: "" },
      { name: "Oregano (sušené, 1 lžička)", qty: null, unit: "" },
      { name: "Drcená rajčata", qty: 400, unit: "g" },
      { name: "Sůl", qty: null, unit: "" },
      { name: "Černý pepř", qty: null, unit: "" },
      { name: "Cukr (1 lžička)", qty: null, unit: "" },
    ],
    steps: [],
  },
  {
    id: makeId(6), createdAt: makeId(6),
    title: "Špagety s pestem ze sušených rajčat",
    description: "Špagety s domácím pestem ze sušených rajčat a vlašských ořechů",
    emoji: "🍝",
    category: "Hlavní jídla",
    prepTime: 30, cookTime: 10,
    difficulty: "Jednoduché",
    servings: 4,
    notes: "https://cookidoo.cz/created-recipes/public/recipes/cs/01FZD4WZ71R5K9TR9K4KGSG0F4",
    ingredients: [
      { name: "Špagety", qty: 500, unit: "g" },
      { name: "Sušená rajčata", qty: 60, unit: "g" },
      { name: "Vlašské ořechy", qty: 60, unit: "g" },
      { name: "Olivový olej", qty: 150, unit: "g" },
      { name: "Parmazán", qty: 75, unit: "g" },
      { name: "Česnek", qty: 2, unit: "ks" },
    ],
    steps: [],
  },
  {
    id: makeId(7), createdAt: makeId(7),
    title: "Horká čokoláda",
    description: "Hustá domácí horká čokoláda",
    emoji: "☕",
    category: "Dezerty",
    prepTime: 7, cookTime: 0,
    difficulty: "Jednoduché",
    servings: 4,
    notes: "https://cookidoo.cz/created-recipes/public/recipes/cs/01KAR28M7GZJ1QJKTXBY7JTKZ8",
    ingredients: [
      { name: "Mléko", qty: 500, unit: "ml" },
      { name: "Kakao (3 lžíce)", qty: null, unit: "" },
      { name: "Cukr (3 lžíce)", qty: null, unit: "" },
      { name: "Škrob (1 lžíce)", qty: null, unit: "" },
    ],
    steps: [],
  },
  {
    id: makeId(8), createdAt: makeId(8),
    title: "Pudingová buchta se zakysanou smetanou",
    description: "Šťavnatá buchta s pudinkovou náplní",
    emoji: "🍰",
    category: "Dezerty",
    prepTime: 20, cookTime: 30,
    difficulty: "Jednoduché",
    servings: 12,
    notes: "https://cookidoo.cz/created-recipes/public/recipes/cs/01KG82JQZD6JHQYZ08B895FDVA",
    ingredients: [
      { name: "Žloutky", qty: 5, unit: "ks" },
      { name: "Bílky", qty: 5, unit: "ks" },
      { name: "Cukr", qty: 250, unit: "g" },
      { name: "Vanilkový cukr", qty: 1, unit: "bal" },
      { name: "Voda", qty: 100, unit: "g" },
      { name: "Olej", qty: 100, unit: "g" },
      { name: "Polohrubá mouka", qty: 300, unit: "g" },
      { name: "Prášek do pečiva", qty: 6, unit: "g" },
      { name: "Kakao (2 lžíce)", qty: null, unit: "" },
      { name: "Plnotučné mléko", qty: 1, unit: "l" },
      { name: "Škrob", qty: 80, unit: "g" },
      { name: "Cukr (puding)", qty: 50, unit: "g" },
      { name: "Vanilka", qty: null, unit: "" },
      { name: "Zakysaná smetana", qty: null, unit: "" },
    ],
    steps: [],
  },
  {
    id: makeId(9), createdAt: makeId(9),
    title: "Čočkové curry s kuřetem",
    description: "Voňavé curry s kuřecím masem a čočkou — čočku namočit přes noc",
    emoji: "🍛",
    category: "Hlavní jídla",
    prepTime: 10, cookTime: 25,
    difficulty: "Jednoduché",
    servings: 4,
    notes: "Čočku namočit 8 hodin / přes noc.\nhttps://cookidoo.cz/recipes/recipe/cs/r129455",
    ingredients: [
      { name: "Kari prášek (2–4 lžíce)", qty: null, unit: "" },
      { name: "Mletá skořice", qty: null, unit: "" },
      { name: "Sladká paprika (1 lžíce)", qty: null, unit: "" },
      { name: "Mletý zázvor (1 lžička)", qty: null, unit: "" },
      { name: "Čerstvý zázvor (1 lžička)", qty: null, unit: "" },
      { name: "Cukr (1 lžička)", qty: null, unit: "" },
      { name: "Sůl (1 lžička)", qty: null, unit: "" },
      { name: "Cayenský pepř (½–1 lžičky)", qty: null, unit: "" },
      { name: "Olivový olej", qty: 30, unit: "g" },
      { name: "Česnek", qty: 2, unit: "ks" },
      { name: "Cibule", qty: 40, unit: "g" },
      { name: "Bobkový list", qty: 1, unit: "ks" },
      { name: "Rajčatový protlak", qty: 20, unit: "g" },
      { name: "Bílý jogurt", qty: 200, unit: "g" },
      { name: "Kokosové mléko", qty: 200, unit: "g" },
      { name: "Citronová šťáva", qty: 20, unit: "ml" },
      { name: "Kuřecí prsa", qty: 600, unit: "g" },
      { name: "Zelená čočka (namočená)", qty: 300, unit: "g" },
    ],
    steps: [],
  },
  {
    id: makeId(10), createdAt: makeId(10),
    title: "Hovězí Stroganoff",
    description: "Klasický ruský guláš se zakysanou smetanou a žampiony",
    emoji: "🥩",
    category: "Hlavní jídla",
    prepTime: 10, cookTime: 25,
    difficulty: "Jednoduché",
    servings: 4,
    notes: "https://cookidoo.cz/recipes/recipe/cs/r400448",
    ingredients: [
      { name: "Hovězí svíčková", qty: 700, unit: "g" },
      { name: "Cibule", qty: 180, unit: "g" },
      { name: "Žampiony", qty: 200, unit: "g" },
      { name: "Máslo", qty: 30, unit: "g" },
      { name: "Rajčatový protlak", qty: 50, unit: "g" },
      { name: "Bílé víno", qty: 100, unit: "g" },
      { name: "Zakysaná smetana", qty: 120, unit: "g" },
      { name: "Mletá paprika (1 lžíce)", qty: null, unit: "" },
      { name: "Dijonská hořčice (1 lžička)", qty: null, unit: "" },
      { name: "Hovězí bujón (pro 0,5 l)", qty: 1, unit: "ks" },
      { name: "Kukuřičný škrob (1 lžíce)", qty: null, unit: "" },
      { name: "Petrželka", qty: null, unit: "" },
      { name: "Sůl", qty: null, unit: "" },
      { name: "Cayenský pepř", qty: null, unit: "" },
    ],
    steps: [],
  },
  {
    id: makeId(11), createdAt: makeId(11),
    title: "Farfalle ai quattro formaggi",
    description: "Těstoviny ve čtyřsýrové omáčce",
    emoji: "🧀",
    category: "Hlavní jídla",
    prepTime: 15, cookTime: 10,
    difficulty: "Jednoduché",
    servings: 4,
    notes: "Fontinu nebo taleggio lze nahradit jiným sýrem.\nhttps://cookidoo.cz/recipes/recipe/cs/r135233",
    ingredients: [
      { name: "Parmazán", qty: 50, unit: "g" },
      { name: "Gorgonzola", qty: 50, unit: "g" },
      { name: "Fontina (nebo náhrada)", qty: 50, unit: "g" },
      { name: "Gruyère", qty: 50, unit: "g" },
      { name: "Taleggio (nebo brie)", qty: 50, unit: "g" },
      { name: "Mléko", qty: 50, unit: "g" },
      { name: "Máslo", qty: 50, unit: "g" },
      { name: "Farfalle", qty: 320, unit: "g" },
    ],
    steps: [],
  },
  {
    id: makeId(12), createdAt: makeId(12),
    title: "Těstovinový salát Caprese",
    description: "Studený těstovinový salát s pestovým dresinkem, kuřetem a mozzarellou",
    emoji: "🥗",
    category: "Hlavní jídla",
    prepTime: 15, cookTime: 10,
    difficulty: "Jednoduché",
    servings: 6,
    notes: "https://cookidoo.cz/recipes/recipe/cs/r634435",
    ingredients: [
      { name: "Parmazán", qty: 50, unit: "g" },
      { name: "Pražené piniové oříšky", qty: 20, unit: "g" },
      { name: "Čerstvá bazalka", qty: 40, unit: "g" },
      { name: "Extra panenský olivový olej", qty: 80, unit: "g" },
      { name: "Citronová šťáva", qty: 25, unit: "g" },
      { name: "Česnek", qty: 1, unit: "ks" },
      { name: "Sůl", qty: null, unit: "" },
      { name: "Těstoviny farfalle nebo fusilli", qty: 300, unit: "g" },
      { name: "Kuřecí prsa", qty: 500, unit: "g" },
      { name: "Cherry rajčata", qty: 250, unit: "g" },
      { name: "Malé kuličky mozzarelly", qty: 250, unit: "g" },
      { name: "Mozzarella", qty: 250, unit: "g" },
      { name: "Černý pepř", qty: null, unit: "" },
    ],
    steps: [],
  },
  {
    id: makeId(13), createdAt: makeId(13),
    title: "Citrónovo-bazalkové kuře s ricottou",
    description: "Kuřecí penne z jednoho hrnce s ricottou a citrónem",
    emoji: "🍋",
    category: "Hlavní jídla",
    prepTime: 10, cookTime: 20,
    difficulty: "Jednoduché",
    servings: 4,
    notes: "https://cookidoo.cz/recipes/recipe/cs/r752530",
    ingredients: [
      { name: "Parmazán", qty: 50, unit: "g" },
      { name: "Čerstvá petrželka", qty: 10, unit: "g" },
      { name: "Čerstvá bazalka", qty: 15, unit: "g" },
      { name: "Česnek", qty: 2, unit: "ks" },
      { name: "Olivový olej", qty: 30, unit: "ml" },
      { name: "Kuřecí prsa", qty: 400, unit: "g" },
      { name: "Voda", qty: 1150, unit: "ml" },
      { name: "Kuřecí bujón (pro 0,5 l)", qty: 2, unit: "ks" },
      { name: "Penne rigate", qty: 400, unit: "g" },
      { name: "Citron", qty: 1, unit: "ks" },
      { name: "Ricotta", qty: 150, unit: "g" },
      { name: "Sůl", qty: null, unit: "" },
    ],
    steps: [],
  },
  {
    id: makeId(14), createdAt: makeId(14),
    title: "Banánový chlebíček (bez cukru)",
    description: "Vlhký banánový chlebíček slazený banány a rozinkami",
    emoji: "🍌",
    category: "Dezerty",
    prepTime: 10, cookTime: 80,
    difficulty: "Jednoduché",
    servings: 10,
    notes: "https://cookidoo.cz/recipes/recipe/cs/r118425",
    ingredients: [
      { name: "Celozrnná mouka", qty: 250, unit: "g" },
      { name: "Prášek do pečiva", qty: 1, unit: "bal" },
      { name: "Mletá skořice (2–3 lžičky)", qty: null, unit: "" },
      { name: "Rozinky", qty: 150, unit: "g" },
      { name: "Velmi zralé banány", qty: 6, unit: "ks" },
      { name: "Rozpuštěné máslo", qty: 100, unit: "g" },
      { name: "Vanilkový extrakt", qty: null, unit: "" },
      { name: "Vejce", qty: 2, unit: "ks" },
      { name: "Mléko (2 lžíce)", qty: null, unit: "" },
    ],
    steps: [],
  },
  {
    id: makeId(15), createdAt: makeId(15),
    title: "Zapečené těstoviny s tuňákem a rajčaty",
    description: "Sytné zapečené fusilli s tuňákem, rajčaty a sýrem",
    emoji: "🐟",
    category: "Hlavní jídla",
    prepTime: 20, cookTime: 40,
    difficulty: "Jednoduché",
    servings: 6,
    notes: "https://cookidoo.cz/recipes/recipe/cs/r695893",
    ingredients: [
      { name: "Fusilli", qty: 500, unit: "g" },
      { name: "Gouda", qty: 200, unit: "g" },
      { name: "Česnek", qty: 2, unit: "ks" },
      { name: "Drcená rajčata", qty: 400, unit: "g" },
      { name: "Smetana (30 % tuk)", qty: 200, unit: "g" },
      { name: "Zakysaná smetana (12 %)", qty: 200, unit: "g" },
      { name: "Rajčatový protlak", qty: 50, unit: "g" },
      { name: "Zeleninový bujón (pro 0,5 l)", qty: 2, unit: "ks" },
      { name: "Rajčata", qty: null, unit: "" },
      { name: "Tuňák v nálevu", qty: 3, unit: "ks" },
      { name: "Červená cibule", qty: null, unit: "" },
      { name: "Sůl", qty: null, unit: "" },
      { name: "Černý pepř", qty: null, unit: "" },
      { name: "Provensálské koření", qty: null, unit: "" },
    ],
    steps: [],
  },
  {
    id: makeId(16), createdAt: makeId(16),
    title: "Paprikový guláš na červeném víně s knedlíkem",
    description: "Hovězí guláš s červeným vínem a domácím houskovým knedlíkem",
    emoji: "🍷",
    category: "Hlavní jídla",
    prepTime: 20, cookTime: 65,
    difficulty: "Střední",
    servings: 6,
    notes: "https://cookidoo.cz/recipes/recipe/cs/r130849",
    ingredients: [
      { name: "Čerstvé droždí", qty: 20, unit: "g" },
      { name: "Mléko (knedlík)", qty: 150, unit: "g" },
      { name: "Hladká mouka", qty: 320, unit: "g" },
      { name: "Vejce", qty: 1, unit: "ks" },
      { name: "Houska", qty: 1, unit: "ks" },
      { name: "Česnek", qty: 2, unit: "ks" },
      { name: "Cibule", qty: 400, unit: "g" },
      { name: "Olej", qty: 40, unit: "g" },
      { name: "Hovězí maso na guláš", qty: 650, unit: "g" },
      { name: "Rajčata", qty: 300, unit: "g" },
      { name: "Červené víno", qty: 250, unit: "g" },
      { name: "Červená paprika (3 lžíce)", qty: null, unit: "" },
      { name: "Kmín (mletý, ½ lžičky)", qty: null, unit: "" },
      { name: "Majoránka (1 lžíce)", qty: null, unit: "" },
      { name: "Bobkové listy", qty: 3, unit: "ks" },
      { name: "Voda", qty: 150, unit: "g" },
      { name: "Červená a zelená paprika", qty: 400, unit: "g" },
      { name: "Sůl", qty: null, unit: "" },
      { name: "Černý pepř", qty: null, unit: "" },
      { name: "Cukr", qty: null, unit: "" },
    ],
    steps: [],
  },
  {
    id: makeId(17), createdAt: makeId(17),
    title: "Fazolový guláš s klobásou",
    description: "Sytný fazolový guláš s uzenou slaninou a klobásou",
    emoji: "🫘",
    category: "Hlavní jídla",
    prepTime: 15, cookTime: 60,
    difficulty: "Jednoduché",
    servings: 5,
    notes: "Fazole namočit 10–12 hodin předem.\nhttps://cookidoo.cz/recipes/recipe/cs/r76800",
    ingredients: [
      { name: "Bílé nebo červené fazole (namočené)", qty: 250, unit: "g" },
      { name: "Voda", qty: 2150, unit: "ml" },
      { name: "Cibule", qty: 120, unit: "g" },
      { name: "Vepřové sádlo", qty: 30, unit: "g" },
      { name: "Uzená slanina", qty: 150, unit: "g" },
      { name: "Klobása", qty: 150, unit: "g" },
      { name: "Červená paprika (1 lžička)", qty: null, unit: "" },
      { name: "Brambory", qty: 200, unit: "g" },
      { name: "Hovězí bujón", qty: 1, unit: "ks" },
      { name: "Sůl", qty: null, unit: "" },
      { name: "Černý pepř", qty: null, unit: "" },
      { name: "Hladká mouka (zahustit)", qty: 15, unit: "g" },
      { name: "Pažitka (ozdoba)", qty: null, unit: "" },
    ],
    steps: [],
  },
];

async function main() {
  const getRes = await fetch(API_URL, { headers: { 'X-Token': API_TOKEN }, cache: 'no-store' });
  if (!getRes.ok) throw new Error('GET failed: ' + getRes.status);
  const existing = await getRes.json();

  // Replace any previously seeded recipes (same BASE_ID range), keep manually added ones
  const manual = Array.isArray(existing)
    ? existing.filter(r => r.id < BASE_ID || r.id > BASE_ID + 100000)
    : [];

  const combined = [...manual, ...recipes];

  const postRes = await fetch(API_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-Token': API_TOKEN },
    body: JSON.stringify(combined),
  });
  if (!postRes.ok) throw new Error('POST failed: ' + postRes.status);
  const result = await postRes.json();
  console.log('Done:', result, `— ${combined.length} recipes total (${manual.length} manual + ${recipes.length} seeded)`);
}

main().catch(e => { console.error(e); process.exit(1); });
