on: push

name: 🚀 Deploy website on PR merge

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: 185.102.21.251
        port: 21
        username: michalovic.endora.site
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
